#!/bin/sh
# amalgamate.sh - Combine all axt sources into a single axt.c file
# Usage: sh amalgamate.sh
# After running: cc axt.c -lpthread -o axt

set -e

SRCDIR=src
OUTPUT=axt.c

# Step 1: Generate parser and lexer from flex/bison sources
echo "Generating parser..." >&2
bison -d -o "$SRCDIR/parser.c" "$SRCDIR/parser.y"
echo "Generating lexer..." >&2
flex -o "$SRCDIR/lexer.c" "$SRCDIR/lexer.l"

echo "Amalgamating into $OUTPUT..." >&2

# POSIX-only headers that need #ifndef _WIN32 guards
POSIX_HEADERS="pthread.h unistd.h sys/stat.h sys/types.h sys/wait.h dirent.h poll.h"

# Windows-only headers that need #ifdef _WIN32 guards
WIN32_HEADERS="windows.h direct.h"

is_posix_header() {
    for h in $POSIX_HEADERS; do
        if [ "$1" = "$h" ]; then
            return 0
        fi
    done
    return 1
}

is_win32_header() {
    for h in $WIN32_HEADERS; do
        if [ "$1" = "$h" ]; then
            return 0
        fi
    done
    return 1
}

# Step 2: Collect all system includes from all source files
collect_system_includes() {
    ALL_INCLUDES=$(cat \
        "$SRCDIR/ast.h" \
        "$SRCDIR/ast.c" \
        "$SRCDIR/varexpand.h" \
        "$SRCDIR/varexpand.c" \
        "$SRCDIR/envfile.h" \
        "$SRCDIR/envfile.c" \
        "$SRCDIR/os_compat.h" \
        "$SRCDIR/os_compat.c" \
        "$SRCDIR/runner.h" \
        "$SRCDIR/runner.c" \
        "$SRCDIR/threadpool.h" \
        "$SRCDIR/threadpool.c" \
        "$SRCDIR/progress.h" \
        "$SRCDIR/progress.c" \
        "$SRCDIR/parser.c" \
        "$SRCDIR/parser.h" \
        "$SRCDIR/lexer.c" \
        "$SRCDIR/main.c" \
    | grep '^#include <' | sort -u)

    # Emit portable headers first
    echo "$ALL_INCLUDES" | while IFS= read -r line; do
        header=$(echo "$line" | sed 's/#include <\(.*\)>/\1/')
        if ! is_posix_header "$header" && ! is_win32_header "$header"; then
            echo "$line"
        fi
    done

    # Emit POSIX headers with #ifndef _WIN32 guards
    POSIX_FOUND=$(echo "$ALL_INCLUDES" | while IFS= read -r line; do
        header=$(echo "$line" | sed 's/#include <\(.*\)>/\1/')
        if is_posix_header "$header"; then
            echo "$line"
        fi
    done)

    if [ -n "$POSIX_FOUND" ]; then
        echo "#ifndef _WIN32"
        echo "$POSIX_FOUND"
        echo "#endif"
    fi

    # Emit Windows headers with #ifdef _WIN32 guards
    WIN32_FOUND=$(echo "$ALL_INCLUDES" | while IFS= read -r line; do
        header=$(echo "$line" | sed 's/#include <\(.*\)>/\1/')
        if is_win32_header "$header"; then
            echo "$line"
        fi
    done)

    if [ -n "$WIN32_FOUND" ]; then
        echo "#ifdef _WIN32"
        echo "$WIN32_FOUND"
        echo "#endif"
    fi
}

# Step 3: Strip local includes and system includes from a file
strip_includes() {
    sed -e '/^#include "/d' -e '/^#include <.*>/d' "$1"
}

# Step 4: Strip include guards from header files
strip_guards() {
    sed -e '/^#ifndef AXT_/d' -e '/^#define AXT_/d' -e '/^#endif.*AXT_/d' "$1"
}

# Step 5: Strip everything from header that's already handled
strip_header() {
    sed -e '/^#ifndef AXT_/d' \
        -e '/^#define AXT_/d' \
        -e '/^#endif.*AXT_/d' \
        -e '/^#include "/d' \
        -e '/^#include <.*>/d' \
        -e '/^#define WIN32_LEAN_AND_MEAN$/d' \
        "$1"
}

# Step 6: Strip local includes and WIN32_LEAN_AND_MEAN (moved to top) from C file
strip_local_includes() {
    sed -e '/^#include "/d' -e '/^#include <.*>/d' \
        -e '/^#define WIN32_LEAN_AND_MEAN$/d' "$1"
}

# Build the amalgamated file
{
    echo "/* axt.c - amalgamated single-file build */"
    echo "/* Generated by amalgamate.sh - do not edit */"
    echo ""
    echo "#ifdef _WIN32"
    echo "#define WIN32_LEAN_AND_MEAN"
    echo "#endif"
    echo ""

    # System includes (deduplicated)
    collect_system_includes
    echo ""

    # Header files (type definitions and declarations)
    echo "/* === ast.h === */"
    strip_header "$SRCDIR/ast.h"
    echo ""

    echo "/* === varexpand.h === */"
    strip_header "$SRCDIR/varexpand.h"
    echo ""

    echo "/* === envfile.h === */"
    strip_header "$SRCDIR/envfile.h"
    echo ""

    echo "/* === os_compat.h === */"
    strip_header "$SRCDIR/os_compat.h"
    echo ""

    echo "/* === runner.h === */"
    strip_header "$SRCDIR/runner.h"
    echo ""

    echo "/* === threadpool.h === */"
    strip_header "$SRCDIR/threadpool.h"
    echo ""

    echo "/* === progress.h === */"
    strip_header "$SRCDIR/progress.h"
    echo ""

    # Parser header (token definitions needed by lexer)
    echo "/* === parser.h === */"
    strip_local_includes "$SRCDIR/parser.h"
    echo ""

    # Implementation files
    echo "/* === ast.c === */"
    strip_local_includes "$SRCDIR/ast.c"
    echo ""

    echo "/* === varexpand.c === */"
    strip_local_includes "$SRCDIR/varexpand.c"
    echo ""

    echo "/* === envfile.c === */"
    strip_local_includes "$SRCDIR/envfile.c"
    echo ""

    echo "/* === os_compat.c === */"
    strip_local_includes "$SRCDIR/os_compat.c"
    echo ""

    echo "/* === threadpool.c === */"
    strip_local_includes "$SRCDIR/threadpool.c"
    echo ""

    echo "/* === progress.c === */"
    strip_local_includes "$SRCDIR/progress.c"
    echo ""

    echo "/* === runner.c === */"
    strip_local_includes "$SRCDIR/runner.c"
    echo ""

    # Parser (bison-generated) - strip includes
    echo "/* === parser.c (bison-generated) === */"
    strip_local_includes "$SRCDIR/parser.c"
    echo ""

    # Lexer (flex-generated) - strip includes
    echo "/* === lexer.c (flex-generated) === */"
    strip_local_includes "$SRCDIR/lexer.c"
    echo ""

    # Main
    echo "/* === main.c === */"
    strip_local_includes "$SRCDIR/main.c"

} > "$OUTPUT"

echo "Done. Build with: cc $OUTPUT -lpthread -o axt" >&2
